:doctype: book

Chapter 21 - The XFS and BRTFS Filesystems

= Chapter 21 - The XFS and BRTFS Filesystems

== Chapter 21 Introduction

The XFS and btrfs filesystems have arisen as important challengers to the dominance of ext4 in Enterprise Linux distributions.
These next generation filesystems have robust capabilities with respect to handling large sizes, spanning multiple physical and logical volumes and performance metrics.

== Learning Objectives

By the end of this chapter, you should be able to:

* Describe the XFS filesystem.
* Maintain the XFS filesystem.
* Describe the btrfs filesystem.

== XFS

The XFS filesystem was designed and created by Silicon Graphics Inc.
(SGI) and used in the IRIX operating system and was subsequently ported to Linux.
It was engineered to deal with large data sets for SGI systems, as well as handle parallel I/O tasks very effectively.

It can handle:

* Up to 16 EB (exabytes) for the total filesystem
* Up to 8 EB for an individual file.

High performance is one of the key design elements of XFS, which implements methods for:

* Employing DMA (Direct Memory Access) I/O
* Guaranteeing an I/O rate
* Adjusting stripe size to match underlying RAID or LVM storage devices.

Unlike other Linux filesystems, XFS can also journal quota information.
This leads to decreased recovery time when a quota-enabled filesystem is uncleanly unmounted.
Furthermore, the journal can be on an external device.

As with other UNIX and Linux filesystems, XFS supports extended attributes.

Maintaining an XFS filesystem is made easier by the fact that most of the maintenance tasks can be done online (i.e., while the filesystem is fully mounted).
These include:

* Defragmenting
* Resizing (enlarge only)
* Dumping/Restoring.

Backup and restore can be done with the native XFS utilities:

* `xfsdump`
* `xfsrestore`

which can be conveniently paused and then resumed at a later time.
Because these utility programs are also multi-threaded, XFS dumps and restores can be accomplished very quickly.

The traditional quota commands can be used to manipulate per-filesystem quotas on an XFS volume.
However, if you use the xfs_quota command, you can use the per-directory quotas that XFS supports.

The XFS filesystem does not directly support hardware or software snapshots.
However, the `xfs_freeze` utility can be used to quiesce the filesystem to allow for a snapshot tool to work on the underlying device.
The Linux LVM tools will automatically use `xfs_freeze` to quiesce the filesystem for snapshots.

== btrfs

Both Linux developers and Linux users with high performance and high capacity or specialized needs are following the development and gradual deployment of the btrfs filesytem, which was created by Chris Mason.
The name stands for B-tree file system.
Full documentation can be found on the https://btrfs.wiki.kernel.org/index.php/Main_Page[btrfs wiki page].

btrfs is intended to address the lack of pooling, snapshots, checksums, and integral multi-device spanning in other Linux filesystems such as ext4.
Such features can be crucial for Linux to scale into larger enterprise storage configurations.

While btrfs has been in the mainline kernel since 2.6.29, it has generally been viewed as experimental.
However, some vendors are using it in new products and it is the default root filesystem on SLES and OpenSUSE.

One of the main features is the ability to take frequent snapshots of entire filesystems, or sub-volumes of entire filesystems in virtually no time.
Because btrfs makes extensive use of COW techniques (Copy on Write), such a snapshot does not involve any more initial space for data blocks or any I/O activity except for some metadata updating.

One can easily revert to the state described by earlier snapshots and even induce the kernel to reboot off an earlier root filesystem snapshot.

btrfs maintains its own internal framework for adding or removing new partitions and/or physical media to existing filesystems, much as LVM (Logical Volume Management) does.

Before btrfs becomes suitable for day-to-day use in critical filesystems, some tasks require finishing.
For a review of the development history of btrfs and expected evolution see the https://lwn.net/Articles/575841/[Kernel Development web page].

== Lab 21.1. Finding Out More about XFS

We do not have a detailed lab exercise you can do with xfs;
many systems still will not have the kernel modules and relevant user utilities installed.
However, if your Linux kernel and distribution does support it, you can easily create a filesystem with mkfs -t xfs.

. Does the system support xfs?
`cat /proc/filesystems` to find supported filesystems.
. Review output of man -k xfs.

` ubuntu@ip-172-31-21-230:~$ cat /proc/filesystems   nodev	sysfs nodev	tmpfs nodev	bdev nodev	proc nodev	cgroup nodev	cgroup2 nodev	cpuset nodev	devtmpfs nodev	configfs nodev	debugfs nodev	tracefs nodev	securityfs nodev	sockfs nodev	bpf nodev	pipefs nodev	ramfs nodev	hugetlbfs nodev	devpts 	ext3 	ext2 	ext4 	squashfs 	vfat nodev	ecryptfs 	fuseblk nodev	fuse nodev	fusectl nodev	mqueue nodev	resctrl nodev	pstore nodev	autofs 	xfs 	msdos 	ufs 	btrfs ` `+ ubuntu@ip-172-31-21-230:~$ man -k xfs filesystems (5)      - Linux filesystem types: ext, ext2, ext3, ext4, hpfs, iso9660, JFS, ...
fs (5)               - Linux filesystem types: ext, ext2, ext3, ext4, hpfs, iso9660, JFS, ...
fsck.xfs (8)         - do nothing, successfully fsfreeze (8)         - suspend access to a filesystem (Ext3/4, ReiserFS, JFS, XFS) mkfs.xfs (8)         - construct an XFS filesystem xfs (5)              - layout, mount options, and supported file attributes for the XFS fi...
xfs_admin (8)        - change parameters of an XFS filesystem xfs_bmap (8)         - print block mapping for an XFS file xfs_copy (8)         - copy the contents of an XFS filesystem xfs_db (8)           - debug an XFS filesystem xfs_estimate (8)     - estimate the space that an XFS filesystem will take xfs_freeze (8)       - suspend access to an XFS filesystem xfs_fsr (8)          - filesystem reorganizer for XFS xfs_growfs (8)       - expand an XFS filesystem xfs_info (8)         - display XFS filesystem geometry information xfs_io (8)           - debug the I/O path of an XFS filesystem xfs_logprint (8)     - print the log of an XFS filesystem xfs_mdrestore (8)    - restores an XFS metadump image to a filesystem image xfs_metadump (8)     - copy XFS filesystem metadata to a file xfs_mkfile (8)       - create an XFS file xfs_ncheck (8)       - generate pathnames from i-numbers for XFS xfs_quota (8)        - manage use of quota on XFS filesystems xfs_repair (8)       - repair an XFS filesystem xfs_rtcp (8)         - XFS realtime copy command xfs_scrub (8)        - check and repair the contents of a mounted XFS filesystem xfs_scrub_all (8)    - scrub all mounted XFS filesystems xfs_spaceman (8)     - show free space information about an XFS filesystem +`

== Exercise 21.2: Finding Out More About btrfs

Please Note We do not have a detailed lab exercise you can do with btrfs;
many systems still will not have the kernel modules and relevant user utilities installed.
However, if your Linux kernel and distribution support it, you can easily create a filesystem with mkfs -t btrfs.

``` ubuntu@ip-172-31-21-230:~$ dd if=/dev/zero of=imagefile_btrfs_test bs=1M count=1024 1024+0 records in 1024+0 records out 1073741824 bytes (1.1 GB, 1.0 GiB) copied, 13.8811 s, 77.4 MB/s ubuntu@ip-172-31-21-230:~$ sudo mkdir /tmp/btrfs_test ubuntu@ip-172-31-21-230:~$ sudo mkfs.btrfs imagefile_btrfs_test  btrfs-progs v5.4.1  See http://btrfs.wiki.kernel.org for more information.

Label:              (null) UUID:               36f52196-ef42-4c59-ac39-e062c7bbe3de Node size:          16384 Sector size:        4096 Filesystem size:    1.00GiB Block group profiles:   Data:             single            8.00MiB   Metadata:         DUP              51.19MiB   System:           DUP               8.00MiB SSD detected:       no Incompat features:  extref, skinny-metadata Checksum:           crc32c Number of devices:  1 Devices:    ID        SIZE  PATH     1     1.00GiB  imagefile_btrfs_test

ubuntu@ip-172-31-21-230:~$ sudo mount imagefile_btrfs_test /tmp/btrfs_test/ ubuntu@ip-172-31-21-230:~$ mount |grep btrfs /home/ubuntu/imagefile_btrfs_test on /tmp/btrfs_test type btrfs (rw,relatime,ssd,space_cache,subvolid=5,subvol=/) ubuntu@ip-172-31-21-230:~$ sudo df -h /tmp/btrfs_test/ Filesystem      Size  Used Avail Use% Mounted on /dev/loop2      1.0G  3.5M  905M   1% /tmp/btrfs_test

ubuntu@ip-172-31-21-230:~$ btrfs usage: btrfs [--help] [--version] [--format +++<format>+++] +++<group>+++[+++<group>+++\...] +++<command>++++++</command>+++ [+++<args>+++]+++</args>++++++</group>++++++</group>++++++</format>+++

Command groups:   subvolume         manage subvolumes: create, delete, list, etc   filesystem        overall filesystem tasks and information   balance           balance data across devices, or change block groups using filters   device            manage and query devices in the filesystem   scrub             verify checksums of data and metadata   rescue            toolbox for specific rescue operations   inspect-internal  query various internal information   property          modify properties of filesystem objects   quota             manage filesystem quota settings   qgroup            manage quota groups   replace           replace a device in the filesystem

Commands:   check             Check structural integrity of a filesystem (unmounted).
restore           Try to restore files from a damaged filesystem (unmounted)   send              Send the subvolume(s) to stdout.
receive           Receive subvolumes from a stream   help              Display help information   version           Display btrfs-progs version

For an overview of a given command use 'btrfs command --help' or 'btrfs [command\...] --help --full' to print all available options.
Any command name can be shortened as far as it stays unambiguous, however it is recommended to use full command names in scripts.
All command groups have their manual page named 'btrfs-+++<group>+++'.
ubuntu@ip-172-31-21-230:~$ df -h Filesystem Size Used Avail Use% Mounted on /dev/root 7.7G 4.6G 3.2G 59% / devtmpfs 484M 0 484M 0% /dev tmpfs 490M 0 490M 0% /dev/shm tmpfs 98M 812K 98M 1% /run tmpfs 5.0M 0 5.0M 0% /run/lock tmpfs 490M 0 490M 0% /sys/fs/cgroup /dev/loop0 33M 33M 0 100% /snap/amazon-ssm-agent/2996 /dev/loop1 34M 34M 0 100% /snap/amazon-ssm-agent/3552 /dev/loop3 99M 99M 0 100% /snap/core/10823 /dev/loop4 56M 56M 0 100% /snap/core18/1944 /dev/loop5 56M 56M 0 100% /snap/core18/1988 /dev/loop6 70M 70M 0 100% /snap/lxd/19032 /dev/loop7 70M 70M 0 100% /snap/lxd/19188 /dev/loop8 100M 100M 0 100% /snap/core/10859 tmpfs 98M 0 98M 0% /run/user/1000 /dev/loop2 1.0G 3.5M 905M 1% /tmp/btrfs_test ubuntu@ip-172-31-21-230:~$ ```+++</group>+++
