:doctype: book

Chapter 22 - Encrypting Disks

= Chapter 22 - Encrypting Disks

== Chapter 22 Introduction

Filesystems may be encrypted to protect them from both prying eyes and attempts to corrupt the data they contain.
Encryption can be chosen at installation or incorporated later.
Linux distributions most often use the LUKS method and perform encryption-related tasks using cryptsetup.

== Learning Objectives

By the end of this chapter, you should be able to:

* Provide sound reasons for using encryption and know when it is called for.
* Understand how LUKS operates through the use of cryptsetup.
* Set up and use encrypted filesystems and partitions.
* Configure the system to mount encrypted partitions at boot.

== Why Use Encryption?

Encryption should be used wherever sensitive data is being stored and transmitted.
Configuring and using block device level encryption provides one of the strongest protections against harm caused by loss or compromise of data contained in hard drives and other media.

Modern Linux distributions offer the choice of encrypting all or some of your disk partitions during installation.
It is also straightforward to create and format encrypted partitions at a later time, but *_you cannot encrypt an already existing partition in place without a data copying operation._*

== LUKS

Modern Linux distributions provide block device level encryption mainly through the use of *LUKS (Linux Unified Key Setup)*.
Using block device encryption is highly recommended for portable systems such as laptops, tablets, and smart phones.

LUKS is installed on top of cryptsetup, a powerful utility that can also use other methods, such as plain dm-crypt volumes, loop-AES and TrueCrypt-compatible format.
We will not discuss these alternatives, as LUKS (which was originally designed for Linux, but has also been exported to other operating systems) is the standard method most often used in Linux.

The dm-crypt kernel module uses the device mapper kernel infrastructure that is also heavily used by LVM, which we will discuss later.

Because LUKS stores all necessary information in the partition header itself, it is rather easy to migrate partitions to other disks or systems.

LUKS can also be used to transparently encrypt swap partitions.

== cryptsetup

Basically, everything is done with the Swiss army knife program `cryptsetup`.
Once encrypted volumes have been set up, they can be mounted and unmounted with normal disk utilities.

The general form of a command is:

cryptsetup [OPTION\...] +++<action>++++++<action-specific>++++++</action-specific>++++++</action>+++

and a rather full listing of possibilities can be generated by:

`$ cryptsetup --help`

`+ cryptsetup 2.0.6 Usage: cryptsetup [OPTION...] <action> <action-specific> --version Print package version -v, --verbose Shows more detailed error messages --debug Show debug messages -c, --cipher=STRING The cipher used to encrypt the disk (see /proc/crypto) -h, --hash=STRING The hash used to create the encryption key from the passphrase -y, --verify-passphrase Verifies the passphrase by asking for it twice -d, --key-file=STRING Read the key from a file --master-key-file=STRING Read the volume (master) key from file.
--dump-master-key Dump volume (master) key instead of keyslots info ....
+`

== Using an Encrypted Partition

If the partition `/dev/sdc12` already exists, the following commands will set up encryption, make it available to LUKS, format it, mount it, use it, and unmount it.

First, we need to give the partition to LUKS:

`$ sudo cryptsetup luksFormat /dev/sdc12`

You will be prompted for a passphrase that will need to open the use of the encrypted volume later.
Note that you only have to do this step once, when setting up encryption.
Your kernel may not support the default encryption method used by cryptsetup.
In that case, you can examine `/proc/crypto` to see the methods your system supports, and then you can supply a method, as in:

`$ sudo cryptsetup luksFormat --cipher aes /dev/sdc12`

You can make the volume available at any time with:

`$ sudo cryptsetup --verbose luksOpen /dev/sdc12 SECRET`

where you will be prompted to supply the passphrase.
You can format the partition:

`$ sudo mkfs.ext4 /dev/mapper/SECRET`

mount it:

`$ sudo mount /dev/mapper/SECRET /mnt`

and then use to your heart's content, just as if it were an unencrypted partition.
When you are done, unmount with:

`$ sudo umount /mnt`

and then remove the association for now:

`$ sudo cryptsetup --verbose luksClose SECRET`

== Mounting at Boot

To mount an encrypted partition at boot, two conditions have to be satisfied.

You need to make an appropriate entry in `/etc/fstab`.
There is nothing special about this and it does not refer to encryption in any way.
This can be as simple as:

`/dev/mapper/SECRET /mnt ext4 defaults 0 0`

You also need to add an entry to `/etc/crypttab`.
This can be as simple as:

`SECRET /dev/sdc12`

You can do more in this file, such as specifying the password if you don't want to be prompted at boot (which seems counterproductive security-wise).
See `man crypttab` to find out what you can do with this file.

== Lab 22.1: Disk Encryption

In this exercise, you will encrypt a partition on the disk in order to provide a measure of security in the event that the hard drive or laptop is stolen.
Reviewing the cryptsetup documentation first would be a good idea (man cryptsetup and cryptsetup --help).

. Create a new partition for the encrypted block device with fdisk.
Make sure the kernel is aware of the new partition table.
A reboot will do this but there are other methods.
. Format the partition with cryptsetup using LUKS for the crypto layer.
. Create the un-encrypted pass through device by opening the encrypted block device, i.e., secret-disk.
. Add an entry to /etc/crypttab so that the system prompts for the passphrase on reboot.
. Format the filesystem as an ext4 filesystem.
. Create a mount point for the new filesystem, i.e.
/secret.
. Add an entry to /etc/fstab so that the filesystem is mounted on boot.
. Try and mount the encrypted filesystem.
. Validate the entire configuration by rebooting.
