:doctype: book

Chapter 4 - Signals

= Chapter 4 - Signals

Created Thursday 21 January 2021

== Introduction

Signals are used to emit notifications for processes to take action in response to often unpredictable events.
These may be caused from within a process itself, or from external events such as other processes.
Many signals are fatal and result in process termination.
However, death sometimes can be averted if program designers decide to handle (subvert) certain termination signals.
Furthermore, many signals are more benign and are just informative or request other kinds of actions.

It is possible to send signals (including those that induce termination) from the command line using:

* kill
* killall
* pkill

== Learning Objectives

By the end of this chapter, you should be able to:

* Explain what signals are and how they are used.
* Discuss the available signals and types of signals available in Linux.
* Use kill, killall and pkill to send signals from the command line.

== What Are Signals?

Signals are one of the oldest methods of Inter-Process Communication (IPC) and are used to notify processes about asynchronous events (or exceptions).

By asynchronous, we mean the signal-receiving process may:

* Not expect the event to occur.
* Expect the event, but not know when it is most likely to occur.

For example, if a user decides to terminate a running program, it could send a signal to the process through the kernel to interrupt and kill the process.

There are two paths by which signals are sent to a process:

* From the kernel to a user process, as a result of an exception or programming error.
* From a user process (using a system call) to the kernel which will then send it to a user process.
The process sending the signal can actually be the same as the one receiving it.

Signals can only be sent between processes owned by the same user or from a process owned by the superuser to any process.

When a process receives a signal, what it does will depend on the way the program is written.
It can take specific actions, coded into the program, to handle the signal or it can just respond according to system defaults.
Two signals (SIGKILL and SIGSTOP) cannot be handled and will always terminate the program.

== Types of Signals

There are a number of different types of signals, and the particular signal sent by the kernel indicates what type of event (or exception) occurred.
Generally, signals are used to handle two things:

Exceptions detected by hardware (such as an illegal memory reference) Exceptions generated by the environment (such as the premature death of a process from the user's terminal).

To see a list of the signals in Linux, along with their numbers, do kill -l, as reflected in this screenshot.
tom@aur6a:~$ kill -l 	 1) SIGHUP	 2) SIGINT	 3) SIGQUIT	 4) SIGILL	 5) SIGTRAP 	 6) SIGABRT	 7) SIGBUS	 8) SIGFPE	 9) SIGKILL	10) SIGUSR1 	11) SIGSEGV	12) SIGUSR2	13) SIGPIPE	14) SIGALRM	15) SIGTERM 	16) SIGSTKFLT	17) SIGCHLD	18) SIGCONT	19) SIGSTOP	20) SIGTSTP 	21) SIGTTIN	22) SIGTTOU	23) SIGURG	24) SIGXCPU	25) SIGXFSZ 	26) SIGVTALRM	27) SIGPROF	28) SIGWINCH	29) SIGIO	30) SIGPWR 	31) SIGSYS	34) SIGRTMIN	35) SIGRTMIN+1	36) SIGRTMIN+2	37) SIGRTMIN+3 	38) SIGRTMIN+4	39) SIGRTMIN+5	40) SIGRTMIN+6	41) SIGRTMIN+7	42) SIGRTMIN+8 	43) SIGRTMIN+9	44) SIGRTMIN+10	45) SIGRTMIN+11	46) SIGRTMIN+12	47) SIGRTMIN+13 	48) SIGRTMIN+14	49) SIGRTMIN+15	50) SIGRTMAX-14	51) SIGRTMAX-13	52) SIGRTMAX-12 	53) SIGRTMAX-11	54) SIGRTMAX-10	55) SIGRTMAX-9	56) SIGRTMAX-8	57) SIGRTMAX-7 	58) SIGRTMAX-6	59) SIGRTMAX-5	60) SIGRTMAX-4	61) SIGRTMAX-3	62) SIGRTMAX-2 	63) SIGRTMAX-1	64) SIGRTMAX	 	tom@aur6a:~$

The signals from SIGRTMIN on are termed real-time signals and are a relatively recent addition.
They have no predefined purpose, and differ in some important ways from normal signals;
they can be queued up and are handled in a FIFO (First In First Out) order.

The meaning attached to the signal type indicates what event caused the signal to be sent (when sent from the kernel).
While users can explicitly send any signal type to one of their processes, the meaning attached may no longer be implied by the signal number or type, and can be used in any way that the process desires.

Typing man 7 signal will give further documentation.

== kill

A process cannot send a signal directly to another process;
it must ask the kernel to send the signal by executing a system call.
Users (including the superuser) can send signals to other processes from the command line or scripts by using kill, as in:

$ kill 1991

$ kill -9 1991

$ kill -SIGKILL 1991

where we are sending a signal to the process with PID = 1991.
If a signal number is not given (as in the first example), the default is to send SIGTERM (15), a terminate signal that can be handled;
the program can take elusive action or clean up after itself, rather than just die immediately.
If this signal is ignored, the user can usually send a SIGKILL (9), which cannot be ignored, to terminate with extreme prejudice.

The name kill is really a bad name, a misnomer that survives for historical reasons.
Although it is often used to kill (terminate) processes, the command's real function is to send any and all signals to processes, even totally benign informative ones.

== killall and pkill

killall kills all processes with a given name, assuming the user has sufficient privilege.
It uses a command name rather than a process ID, and can be done as in:

[source,console]
----
$ killall bash

$ killall -9 bash

$ killall -SIGKILL bash
----

pkill sends a signal to a process using selection criteria:

$ pkill [-signal] [options] [pattern]

For example:

`$ pkill -u libby foobar`

will kill all of libby's processes with a name of foobar.

Another example:

``$ pkill -HUP rsyslogd ``makes rsyslog re-read its configuration file.

MY NOTE: -HUP is not an parameter, but short for SIGHUP (signal hang up).
SIGHUP was originally used after a user hung up a modem on a serial connection, but is used in modern linux distros to reload its config file.
Same is achieved by

`$pkill -1 rsyslogd`

== Lab 4.1

You will need to compile it and run it as in: 	$ gcc -o signals signals.c 	$ ./signals

When run, the program:

* Does not send the signals SIGKILL or SIGSTOP, which can not be handled and will always terminate a program.
* Stores the sequence of signals as they come in, and updates a counter array for each signal that indicates how many

times the signal has been handled.

* Begins by suspending processing of all signals and then installs a new set of signal handlers for all signals.
* Sends every possible signal to itself multiple times and then unblocks signal handling and the queued up signal handlers will be called.
* Prints out statistics including:

-- The total number of times each signal was received.
-- The order in which the signals were received, noting each time the total number of times that signal had been received up to that point.

=== Note the following:

* If more than one of a given signal is raised while the process has blocked it, does the process receive it multiple times?
Does the behavior of real time signals differ from normal signals?
 ** _According to man 7 signal, real-time signals are numbered 32-64.
The DEFAULT action of a RT signal is to terminate the receiving proess.
Multiple instances of RT signals can be queued;
standard signals (1-32) , if blocked while being delivered are only queued once.
Hence, in the output below, signals 1-31 are queued only once._
* Are all signals received by the process, or are some handled before they reach it?
 ** _According to output below, signal 18, SIGCONT, was sent but not queued.
SIGCONT continues child processes, is handled by the operating system, not the application._
* What order are the signals received in?
One signal, SIGCONT (18 on x86 ) may not get through;
can you figure out why?
 ** _As mentioned above, the operating system will handle SIGCONT, not the application._

+
``` ubuntu@ip-172-31-21-230:~/lfs201$ ./signals
+
Installing signal handler and Raising signal for signal number:

  1   2   3   4   5   6   7   8  --  10  11  12  13  14  15  16
 17  18  --  20  21  22  23  24  25  26  27  28  29  30  31  --
 --  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48
 49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64
+
Signal  Number(Times Processed)   --------------------------------------------      1:  1     2:  1     3:  1     4:  1     5:  1     6:  1     7:  1     8:  1 +      9:  0    10:  1    11:  1    12:  1    13:  1    14:  1    15:  1    16:  1 +     17:  1    18:  0    19:  0    20:  1    21:  1    22:  1    23:  1    24:  1 +     25:  1    26:  1    27:  1    28:  1    29:  1    30:  1    31:  1    32:  0 +     33:  0    34:  3    35:  3    36:  3    37:  3    38:  3    39:  3    40:  3 +     41:  3    42:  3    43:  3    44:  3    45:  3    46:  3    47:  3    48:  3 +     49:  3    50:  3    51:  3    52:  3    53:  3    54:  3    55:  3    56:  3 +     57:  3    58:  3    59:  3    60:  3    61:  3    62:  3    63:  3    64:  3
+
History: Signal  Number(Count Processed)   --------------------------------------------

  4(1)   5(1)   7(1)   8(1)  11(1)  31(1)   1(1)   2(1)
  3(1)   6(1)  10(1)  12(1)  13(1)  14(1)  15(1)  16(1)
 17(1)  20(1)  21(1)  22(1)  23(1)  24(1)  25(1)  26(1)
 27(1)  28(1)  29(1)  30(1)  34(1)  34(2)  34(3)  35(1)
 35(2)  35(3)  36(1)  36(2)  36(3)  37(1)  37(2)  37(3)
 38(1)  38(2)  38(3)  39(1)  39(2)  39(3)  40(1)  40(2)
 40(3)  41(1)  41(2)  41(3)  42(1)  42(2)  42(3)  43(1)
 43(2)  43(3)  44(1)  44(2)  44(3)  45(1)  45(2)  45(3)
 46(1)  46(2)  46(3)  47(1)  47(2)  47(3)  48(1)  48(2)
 48(3)  49(1)  49(2)  49(3)  50(1)  50(2)  50(3)  51(1)
 51(2)  51(3)  52(1)  52(2)  52(3)  53(1)  53(2)  53(3)
 54(1)  54(2)  54(3)  55(1)  55(2)  55(3)  56(1)  56(2)
 56(3)  57(1)  57(2)  57(3)  58(1)  58(2)  58(3)  59(1)
 59(2)  59(3)  60(1)  60(2)  60(3)  61(1)  61(2)  61(3)
 62(1)  62(2)  62(3)  63(1)  63(2)  63(3)  64(1)  64(2)
 64(3)
+
```
